version: 2
builds:
  - binary: '{{ .ProjectName }}_v{{ .Version }}'
    env:
      - CGO_ENABLED=0
    goarch:
      - arm64
      - amd64
      - '386'
      - arm
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    ignore:
      - goos: darwin
        goarch: '386'
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  github:
    owner: "petetanton"
    name: "terraform-provider-cachet"
  draft: true
changelog:
  disable: false
