on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 8001:5432
      cachet:
        image: cachethq/docker
        ports:
          - 8000:8000
        env:
          CACHE_DRIVER: database
          QUEUE_DRIVER: database
          SESSION_DRIVER: database
          CACHET_BEACON: false
          DB_DRIVER: pgsql
          DB_HOST: postgres
          DB_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_DATABASE: postgres
          DB_PREFIX: chq_
          APP_KEY: base64:SZF2yuinIPU7Qpi7ZqL+hflPa5eRLQVg2IcQyV+cZxs=
          APP_LOG: errorlog
          APP_ENV: ${APP_ENV:-production}
          APP_DEBUG: false
          DEBUG: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Run tests
        run: |
          TF_ACC=true CACHET_URL=http://localhost:8000 go test -v ./cachet
  docs:
    runs-on: ubuntu-latest
    concurrency: "docs"
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: fetch doc generator
        run: wget https://github.com/hashicorp/terraform-plugin-docs/releases/download/v0.14.0/tfplugindocs_0.14.0_linux_amd64.zip
      - name: unzip
        run: |
          mkdir bin
          unzip tfplugindocs_0.14.0_linux_amd64.zip -d bin
      - name: generate-docs
        run: ./bin/tfplugindocs generate
      - name: commit docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update docs
          file_pattern: 'docs/*'