on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run tests
        run: |
          go build -o main.go
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checko ut@v3
      - name: fetch doc generator
        run: wget https://github.com/hashicorp/terraform-plugin-docs/releases/download/v0.14.0/tfplugindocs_0.14.0_linux_amd64.zip
      - name: unzip
        run: unzip tfplugindocs_0.14.0_linux_amd64.zip
      - name: generate-docs
        run: ./tfplugindocs_0.14.0_linux_amd64/tfplugindocs generate
      - name: commit docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update docs
          file_pattern: 'docs/*'